### ISSUE TITLE
Support /tls/http and /https

### ISSUE THREAD

**Issue by lidel** [multiformats/js-multiaddr-to-uri#5]
`/tls` multicodec was added in: https://github.com/multiformats/multicodec/pull/145

See also https://github.com/tableflip/uri-to-multiaddr/issues/6

**Comment by alanshaw** [comment]
Please send PR 🙏

**Comment by lidel** [comment]
Already on my todo list, but let's land https://github.com/multiformats/js-multiaddr-to-uri/pull/7 first as it touches http as well.

**Comment by achingbrain** [comment]
Fixed by #120
