### ISSUE TITLE
Move to /multiformats org

### ISSUE THREAD

**Issue by lidel** [multiformats/js-multiaddr-to-uri#6]
This library is super useful, used by over 400 projects

TODO:

- [x] move to <del>ipfs-shipyard</del> multiformats org
- [x] add @olizilla  as co-owner on NPM    :running_man:  :dash: :bus:
- [x] https://github.com/tableflip/uri-to-multiaddr/issues/7

:ok_hand:

**Comment by alanshaw** [comment]
Should we move to `multiformats` instead? Also, prefix "js-" on repo name.

**Comment by lidel** [comment]
I'd say yes to both :+1:

**Comment by lidel** [comment]
@alanshaw would it be ok to add @olizilla and @lidel as contributors  at NPM?
https://www.npmjs.com/package/multiaddr-to-uri?

**Comment by alanshaw** [comment]
BTW, it was done a long time ago 😇
