### ISSUE TITLE
Handling of /dnsaddr/example.com

### ISSUE THREAD

**Issue by lidel** [multiformats/js-multiaddr-to-uri#8]
Standalone dnsaddr: 

```js
toUri('/dnsaddr/wikipedia.org')
```
..returns domain name (`wikipedia.org`), not a URI 

@alanshaw is there a reason behind that behavior? 
(I imagine the user of this library expects URI or an error)

**Comment by alanshaw** [comment]
Yes, it should always return a valid URI or throw an error
